repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: ["--check"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [mccabe]
        args: ["--max-line-length", "100", "--max-complexity", "10"]

  #- repo: local
  #  hooks:
  #    - id: pylint
  #      name: pylint
  #      entry: pylint
  #      language: system
  #      types: [python]
  #      args: 
  #        [
  #          "-rn", # Only display messages
  #          "-sn", # Don't display the score
  #        ]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy scope3_methodology
        pass_filenames: false
        verbose: true
        language: system
        types: [python]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
